# Conversion
markdown:         kramdown
highlighter:      rouge

# Markdown Processor
kramdown:
  auto_ids: true
  input: GFM
  hard_wrap: false

url: https://www.shropshirestrummers.co.uk
timezone: GMT

# Permalinks
permalink:        pretty

# Social
title: Shropshire Strummers 
